- name: copy Docker Compose files
  copy:
    src: ./flask_app
    dest: /tmp

- name: Run container
  become: True
  shell:
    cmd: "docker-compose -f ./flask_app/docker-compose.yml  up -d  && bash ./flask_app/sc.sh "
- name: Take readings and put into database
  ansible.builtin.cron:
    name: "fill database"
    minute: "*"
    hour: "*"
    job: "bash /tmp/flask_app/sc.sh"

